package jobs

import (
	"context"
	"fmt"
	"log"
	"os"
	"time"

	"github.com/EsanSamuel/sensory/db"
	"github.com/EsanSamuel/sensory/models"
	"github.com/gocraft/work"
	"github.com/resend/resend-go/v3"
	"go.mongodb.org/mongo-driver/v2/bson"
)

type Context struct {
	UserId  string
	Email   string
	LogId   string
	LogData models.Log
}

func (c *Context) Log(job *work.Job, next work.NextMiddlewareFunc) error {
	fmt.Println("Background job is running:", job.Name, "ID:", job.ID)
	return next()
}

func (c *Context) FindUser(job *work.Job, next work.NextMiddlewareFunc) error {
	if _, ok := job.Args["user_id"]; ok {
		c.Email = job.ArgString("email_addr")
		c.UserId = job.ArgString("user_id")

		var ctx, cancel = context.WithTimeout(context.Background(), 100*time.Second)
		defer cancel()

		err := db.LogCollection.FindOne(ctx, bson.M{"log_id": c.LogId}).Decode(&c.LogData)

		if err != nil {
			log.Println(err)
			return err
		}
		if err := job.ArgError(); err != nil {
			return err
		}
	}
	return next()
}

func (c *Context) SendEmail(job *work.Job) error {
	email := c.Email
	log := c.LogData

	if log.Level != "ERROR" && log.Level != "WARN" {
		return nil
	}

	RESEND_API_KEY := os.Getenv("RESEND_API_KEY")
	if RESEND_API_KEY == "" {
		return fmt.Errorf("RESEND_API_KEY not set")
	}

	client := resend.NewClient(RESEND_API_KEY)

	subject := "⚠️ Warning detected in your app"
	color := "#f59e0b"

	if log.Level == "ERROR" {
		subject = "🚨 Error detected in your app"
		color = "#dc2626"
	}

	html := fmt.Sprintf(`
<div style="max-width:600px;margin:0 auto;font-family:Arial,sans-serif;background:#ffffff;padding:24px;border-radius:8px;border:1px solid #e5e7eb;">
  
  <h2 style="color:%s;text-align:center;margin-bottom:8px;">
    %s Alert
  </h2>

  <p style="text-align:center;color:#374151;">
    An issue was detected in your application.
  </p>

  <hr style="margin:20px 0;" />

  <p><b>Service:</b> %s</p>
  <p><b>Project ID:</b> %s</p>
  <p><b>Level:</b> %s</p>
  <p><b>Message:</b> %s</p>
  <p><b>Timestamp:</b> %s</p>

  <div style="margin-top:16px;padding:12px;background:#f9fafb;border-radius:6px;">
    <p style="margin:0;"><b>File:</b> %s</p>
    <p style="margin:0;"><b>Function:</b> %s</p>
    <p style="margin:0;"><b>Line:</b> %d</p>
  </div>

  <p style="margin-top:24px;color:#6b7280;font-size:14px;text-align:center;">
    This email was automatically generated by your logging system.
  </p>
</div>
`,
		color,
		log.Level,
		log.Service,
		log.ProjectID,
		log.Level,
		log.Message,
		log.TimeStamp,
		log.Runtime.File,
		log.Runtime.Fn,
		log.Runtime.Line,
	)

	params := &resend.SendEmailRequest{
		From:    "Log Tracker <alerts@mikaelsoninitiative.org>",
		To:      []string{email},
		Subject: subject,
		Html:    html,
	}

	sent, err := client.Emails.Send(params)
	if err != nil {
		return err
	}

	fmt.Println("Email sent:", sent.Id)
	return nil
}
